/**
 * TrypheneMart - Products Database (India Region)
 * Product catalog with localized pricing in INR (₹) and Indian grocery items
 */

const productList = [
  {
    id: 1,
    name: "Fresh Shimla Apples",
    category: "fruits-veg",
    categoryName: "Fruits & Vegetables",
    price: 149,
    priceUnit: "per kg",
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    brand: "BioFarm",
    rating: 4.8,
    reviewCount: 124,
    description: "Crispy and sweet organic Shimla apples harvested directly from orchards in Himachal Pradesh. Packed with vitamins and fiber.",
    inStock: true,
    isPromo: true,
    oldPrice: 180
  },
  {
    id: 2,
    name: "Hass Avocados (Pack of 2)",
    category: "fruits-veg",
    categoryName: "Fruits & Vegetables",
    price: 199,
    priceUnit: "pack of 2",
    image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    brand: "NaturePure",
    rating: 4.6,
    reviewCount: 89,
    description: "Ready-to-eat creamy Hass avocados. Rich in healthy fats, perfect for salads, toasts, and homemade guacamole.",
    inStock: true,
    isPromo: false
  },
  {
    id: 3,
    name: "Organic Robusta Bananas",
    category: "fruits-veg",
    categoryName: "Fruits & Vegetables",
    price: 49,
    priceUnit: "per kg",
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    brand: "BioFarm",
    rating: 4.9,
    reviewCount: 210,
    description: "Naturally ripened chemical-free bananas. Great source of potassium, ideal for daily breakfast smoothies.",
    inStock: true,
    isPromo: false
  },
  {
    id: 4,
    name: "Fresh Toned Milk 1L",
    category: "dairy-bakery",
    categoryName: "Dairy & Bakery",
    price: 66,
    priceUnit: "1 Litre pouch",
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    brand: "Amul",
    rating: 4.7,
    reviewCount: 340,
    description: "Pasteurised fresh toned milk fortified with Vitamin A & D. Essential for everyday tea, coffee, and curds.",
    inStock: true,
    isPromo: false
  },
  {
    id: 5,
    name: "Fresh Malai Paneer 200g",
    category: "dairy-bakery",
    categoryName: "Dairy & Bakery",
    price: 115,
    priceUnit: "200g pack",
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    brand: "Amul",
    rating: 4.9,
    reviewCount: 195,
    description: "Soft and wholesome cottage cheese crafted from pure cow milk. Ideal for Shahi Paneer, tikka, and salads.",
    inStock: true,
    isPromo: true,
    oldPrice: 130
  },
  {
    id: 6,
    name: "Natural Set Dahi / Curd 400g",
    category: "dairy-bakery",
    categoryName: "Dairy & Bakery",
    price: 50,
    priceUnit: "400g tub",
    image: "https://images.unsplash.com/photo-1584278860011-61d0066f0c5d?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    brand: "Amul",
    rating: 4.5,
    reviewCount: 162,
    description: "Thick, creamy, and mildly sour set curd. Rich in natural probiotics for healthy gut digestion.",
    inStock: true,
    isPromo: false
  },
  {
    id: 7,
    name: "Spiced Masala Potato Chips",
    category: "snacks",
    categoryName: "Snacks & Munchies",
    price: 40,
    priceUnit: "150g pack",
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    brand: "RoyalGourmet",
    rating: 4.4,
    reviewCount: 98,
    description: "Kettle-cooked crispy potato wafers seasoned with aromatic Indian spices and rock salt.",
    inStock: true,
    isPromo: false
  },
  {
    id: 8,
    name: "Chicken Tikka Club Sandwich",
    category: "snacks",
    categoryName: "Snacks & Munchies",
    price: 169,
    priceUnit: "per unit",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80",
    isVeg: false,
    brand: "RoyalGourmet",
    rating: 4.3,
    reviewCount: 75,
    description: "Fresh wholewheat bread stuffed with smoked chicken tikka chunks, light mayo, and crisp lettuce.",
    inStock: true,
    isPromo: false
  },
  {
    id: 9,
    name: "Tandoori Roasted Chicken Platter",
    category: "snacks",
    categoryName: "Snacks & Munchies",
    price: 299,
    priceUnit: "ready portion",
    image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80",
    isVeg: false,
    brand: "RoyalGourmet",
    rating: 4.8,
    reviewCount: 178,
    description: "Juicy chicken pieces marinated in clay-oven tandoori spices and lemon herbs. Served fresh.",
    inStock: true,
    isPromo: true,
    oldPrice: 349
  },
  {
    id: 10,
    name: "Pure Alphonso Mango Juice 1L",
    category: "beverages",
    categoryName: "Beverages & Teas",
    price: 120,
    priceUnit: "1L bottle",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    brand: "NaturePure",
    rating: 4.7,
    reviewCount: 142,
    description: "Rich pulp juice crafted from authentic Ratnagiri Alphonso mangoes. No added artificial preservatives.",
    inStock: true,
    isPromo: false
  },
  {
    id: 11,
    name: "South Indian Filter Coffee Beans 500g",
    category: "beverages",
    categoryName: "Beverages & Teas",
    price: 380,
    priceUnit: "500g pack",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    brand: "RoyalGourmet",
    rating: 4.9,
    reviewCount: 230,
    description: "Dark roasted Arabica & Robusta coffee beans from Chikmagalur estates. Intense aroma with rich crema.",
    inStock: true,
    isPromo: true,
    oldPrice: 450
  },
  {
    id: 12,
    name: "Eco Surface Cleaner Spray 750ml",
    category: "household",
    categoryName: "Household & Cleaning",
    price: 175,
    priceUnit: "750ml spray",
    image: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    brand: "GreenHome",
    rating: 4.6,
    reviewCount: 54,
    description: "Plant-based biodegradable multi-surface cleaner infused with natural neem and citrus oils.",
    inStock: true,
    isPromo: false
  },
  {
    id: 13,
    name: "Organic Liquid Detergent 2L",
    category: "household",
    categoryName: "Household & Cleaning",
    price: 499,
    priceUnit: "2L bottle (40 washes)",
    image: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    brand: "GreenHome",
    rating: 4.8,
    reviewCount: 142,
    description: "Hypoallergenic liquid detergent tough on stains, gentle on fabrics. Safe for washing machines & hands.",
    inStock: true,
    isPromo: false
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = productList;
}
